eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-production-5876.up.railway.app/eureka
      #defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Gateway
  cloud:
      gateway:
        routes:
          - id: posts
            uri: https://jsonplaceholder.typicode.com
            predicates:
              - Path=/posts/**

  data:
    redis:
      host: viaduct.proxy.rlwy.net
      port: 29501
      username: default
      password: VKBrSpbcHuohzuYioCrcieEOaVBiUJSO
server:
  port: 8765
jwt:
  secret: 57443a4c052350a44638835d64fd66822f813319123132123123sfsafdfsdf57443a4c052350a44638835d64fd66822f813319123132123123sfsafdfsdf
  expiration: 86400


