eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-production-5876.up.railway.app/eureka
      #defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Gateway
  cloud:
      gateway:
        routes:
          - id: posts
            uri: https://jsonplaceholder.typicode.com
            predicates:
              - Path=/posts/**
server:
  port: 8765
